image: Visual Studio 2017
platform: x64
version: '#{build}'
environment:
  matrix:
    # "JOB" doesn't really mean anything special
    - JOB: "Seedminer CPU Brute-forcer | Windows (gcc)"
    - JOB: "bfCL | Windows (gcc)"
matrix:
  fast_finish: true # If one job fails, the whole build is marked as a failure
for:
-
  matrix:
    only:
      - JOB: "Seedminer CPU Brute-forcer | Windows (gcc)"

  install:
  - git submodule update --init --recursive
  - PATH C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-openssl
  build_script:
  - cd seedminer/
  - mingw32-make
for:
-
  matrix:
    only:
      - JOB: "bfCL | Windows (gcc)"

  install:
  - git submodule update --init --recursive
  - PATH C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - vcpkg install opencl:x64-windows
  - copy C:\Tools\vcpkg\packages\opencl_x64-windows\lib\OpenCL.lib C:\msys64\mingw64\lib\
  - robocopy /E C:\Tools\vcpkg\packages\opencl_x64-windows\include\CL\ C:\msys64\mingw64\include\CL\
  build_script:
  - cd bfCL/
  - mingw32-make
