image: Visual Studio 2017
platform:
  - x64
install:
  - PATH C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-openssl
build_script:
  - cd seedminer/
  - mingw32-make
