image: Visual Studio 2017
platform:
  - x64
environment:
  matrix:
    # "JOB" doesn't really mean anything
    - JOB: "Seedminer CPU Brute-forcer | Windows (gcc)"
    - JOB: "bfCL | Windows (gcc)"
install:
  - PATH C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  # Doing full pacman upgrades take too long so we'll just use what packages are already available to us
  - cmd: |
      if "%JOB%" == "Seedminer CPU Brute-forcer | Windows ^(gcc^)" (
          pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-openssl
      ) else (
          pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-mbedtls
      )
build_script:
  - cd seedminer/
  - mingw32-make
