image: Visual Studio 2017
platform: x64
environment:
  matrix:
    # "JOB" doesn't really mean anything
    - JOB: "Seedminer CPU Brute-forcer | Windows (gcc)"
    - JOB: "bfCL | Windows (gcc)"
install:
  - git submodule update --init --recursive
  - PATH C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  # Doing full pacman upgrades takes too long so we'll just use what packages are already available to us
  # Use stderr redirect manipulation
  - ps: |
      if ($env:JOB -eq "Seedminer CPU Brute-forcer | Windows (gcc)") {
          cmd.exe /C pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-openssl 2`>`&1
      } else {
          cmd.exe /C pacman -S --noconfirm --needed mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-mbedtls 2`>`&1
          vcpkg install opencl:x64-windows
          copy C:\Tools\vcpkg\packages\opencl_x64-windows\lib\OpenCL.lib C:\msys64\mingw64\lib\
          robocopy /E C:\Tools\vcpkg\packages\opencl_x64-windows\include\CL C:\msys64\mingw64\include\
          if ($LASTEXITCODE -eq 3) {
              $host.SetShouldExit(0)
          }
      }
build_script:
  - ps: |
      if ($env:JOB -eq "Seedminer CPU Brute-forcer | Windows (gcc)") {
          cd seedminer/
      } else {
          cd bfCL/
      }
  - mingw32-make
