matrix:
  include:
  - name: "bfCL - Ubuntu"
    os: linux
    sudo: required
    language: c
    env:
      - SHARED=1
      - CC=clang
      - CC=gcc
    addons:
      apt:
        packages:
        - ocl-icd-opencl-dev
    # Because Trusty doesn't have mbedtls
    before_install:
      - cd /home/travis/
      - wget https://tls.mbed.org/download/mbedtls-2.12.0-apache.tgz
      - tar -xvf mbedtls-2.12.0-apache.tgz
    install:
      - cd /home/travis/mbedtls-2.12.0/
      - make
      - make check
      - sudo make install
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make

  - name: "bfCL - OS X"
    os: osx
    language: c
    env:
      - CC=clang
      - CC=gcc
    install:
      - brew install mbedtls
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
