matrix:
  include:
  - name: "Seedminer CPU Bruteforcer - Ubuntu (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: false # Take advantage of a container-based environment
    addons:
      apt:
        update: true
        packages:
        - libssl-dev
    script:
      - cd $TRAVIS_BUILD_DIR/seedminer
      - make
  - name: "Seedminer CPU Bruteforcer - macOS (clang)"
    language: c
    compiler: clang
    os: osx
    before_install:
      - brew update
    install:
      - brew install openssl
    script:
      - cd $TRAVIS_BUILD_DIR/seedminer
      - make
  - name: "bfCL - Ubuntu (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: required
    env: SHARED=1 # To build mbedtls shared libs
    before_install:
      - sudo apt-get update
      - cd /home/travis/
      - git clone https://github.com/ARMmbed/mbedtls.git # Needed in order to compile bfCL
      - cd /home/travis/mbedtls/
      - git checkout $(git tag -l --sort -version:refname 'mbedtls-*' | head -n 1) # Checkout highest mbedtls tag version number
    install:
      - make lib
      - make check
      - sudo make install
      - sudo apt-get install -y ocl-icd-opencl-dev # OpenCL Headers & ICD Loader
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
  - name: "bfCL - macOS (clang)"
    language: c
    compiler: clang
    os: osx
    before_install:
      - brew update
    install:
      - brew install mbedtls
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
  - name: "Seedminer Launcher"
    language: python
    python: 3.6
    os: linux
    sudo: false # Take advantage of a container-based environment
    install:
      - pip install --upgrade pyflakes
    script:
      - cd $TRAVIS_BUILD_DIR/seedminer
      - pyflakes seedminer_launcher3.py
  - name: "Seedstarter"
    language: c
    compiler: gcc
    os: linux
    sudo: required
    services: docker
    before_install:
      - cd /home/travis/
      - git clone --recursive https://github.com/Steveice10/bannertool.git
      - cd /home/travis/bannertool/
      - git checkout master
    install:
      - make
      - export PATH=$PATH:/home/travis/bannertool/output/linux-x86_64/
      - docker pull devkitpro/devkitarm
    script:
      - docker run -v $TRAVIS_BUILD_DIR:/seedminer/ devkitpro/devkitarm /bin/bash -ex /seedminer/.travis/docker.sh
