language: generic
matrix:
  include:
  - name: "Seedminer CPU Brute-forcer | Linux (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: false # Use a container-based environment
    addons:
      apt:
        update: true
        packages:
        - libssl-dev
    script:
      - cd seedminer/
      - make

  - name: "Seedminer CPU Brute-forcer | macOS (clang)"
    language: c
    compiler: clang
    os: osx
    install:
      - brew update
      - brew install openssl
    script:
      - cd seedminer/
      - make

  - name: "bfCL | Linux (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: false # Use a container-based environment
    addons:
      apt:
        update: true
        packages:
        - ocl-icd-opencl-dev
    install:
      - vcpkg install mbedtls:x64-linux # Because it's not in Trusty's apt repo
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make

  - name: "bfCL | macOS (clang)"
    language: c
    compiler: clang
    os: osx
    install:
      - brew update
      - brew install mbedtls
    script:
      - cd bfCL/
      - make

  - name: "Seedminer Launcher"
    language: python
    python: 3.6
    os: linux
    sudo: false # Use a container-based environment
    install:
      - pip install pyflakes
    script:
      - cd seedminer/
      - pyflakes seedminer_launcher3.py

  - name: "Seedstarter"
    language: c
    compiler: gcc
    os: linux
    sudo: required
    services: docker
    env: DEP_LOCATION=$TRAVIS_BUILD_DIR/..
    before_install:
      - cd ../
      - git clone --recursive https://github.com/Steveice10/bannertool.git
      - cd bannertool/
      - git checkout master
      - make
      - cd ../
      - git clone --recursive https://github.com/profi200/Project_CTR.git
      - cd Project_CTR/
      - git checkout master
      - cd makerom/
      - make
    install:
      - cd ../../
      - docker pull devkitpro/devkitarm
    script:
      - sudo docker run -v $DEP_LOCATION/bannertool/:/bannertool/ -v $DEP_LOCATION/Project_CTR/makerom/:/makerom/ -v $TRAVIS_BUILD_DIR:/seedminer/ devkitpro/devkitarm /bin/bash -ex /seedminer/.travis/docker.sh
