language: generic
matrix:
  include:
  - name: "Seedminer CPU Brute-forcer | Linux (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: false # Use a container-based environment
    addons:
      apt:
        update: true
        packages:
        - libssl-dev
    script:
      - cd seedminer/
      - make

  - name: "Seedminer CPU Brute-forcer | macOS (clang)"
    language: c
    compiler: clang
    os: osx
    install:
      - brew update
      - brew install openssl
    script:
      - cd seedminer/
      - make

  - name: "bfCL | Linux (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: required
    env: SHARED=1 # To build shared mbedtls libraries
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y ocl-icd-opencl-dev # OpenCL C headers & ICD Loader
    install:
      - cd ..
      - git clone --recursive https://github.com/ARMmbed/mbedtls.git
      - cd mbedtls/
      - git checkout mbedtls-2.12.0
      - make lib
      - make check
      - sudo make install
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make

  - name: "bfCL | macOS (clang)"
    language: c
    compiler: clang
    os: osx
    install:
      - brew update
      - brew install mbedtls
    script:
      - cd bfCL/
      - make

  - name: "Seedminer Launcher"
    language: python
    python: 3.6
    os: linux
    sudo: false # Use a container-based environment
    install:
      - pip install pyflakes
    script:
      - cd seedminer/
      - pyflakes seedminer_launcher3.py

  - name: "Seedstarter"
    language: c
    compiler: gcc
    os: linux
    sudo: required
    services: docker
    before_install:
      - cd ..
      - git clone --recursive https://github.com/Steveice10/bannertool.git
      - cd bannertool/
      - git checkout master
      - make
      - cd ..
      - git clone --recursive https://github.com/profi200/Project_CTR.git
      - cd Project_CTR/
      - git checkout master
      - cd makerom/
      - make
    install:
      - cd ../..
      - docker pull devkitpro/devkitarm
      - ls
    script:
      - sudo docker run -v /home/travis/bannertool/:/bannertool/ -v /home/travis/Project_CTR/makerom/:/makerom/ -v $TRAVIS_BUILD_DIR:/seedminer/ devkitpro/devkitarm /bin/bash -ex /seedminer/.travis/docker.sh
