language: c
compiler:
  - clang
  - gcc
matrix:
  include:
  - name: "bfCL - Ubuntu"
    os: linux
    sudo: required
    env: SHARED=1
    addons:
      apt:
        packages:
        - ocl-icd-opencl-dev
    before_install:
      - cd /home/travis/
      - wget https://tls.mbed.org/download/mbedtls-2.12.0-apache.tgz
      - tar -xvf mbedtls-2.12.0-apache.tgz
    install:
      - cd /home/travis/mbedtls-2.12.0/
      - make
      - make check
      - sudo make install
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
  - name: "bfCL - OS X"
    os: osx
    install:
      - brew install mbedtls
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
