matrix:
  include:
  - name: "Seedminer CPU Bruteforcer - Ubuntu (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: false # Take advantage of a container-based environment
    addons:
      apt:
        packages:
        - libssl-dev
    script:
      - cd $TRAVIS_BUILD_DIR/seedminer
      - make
  - name: "Seedminer CPU Bruteforcer - macOS (clang)"
    language: c
    compiler: clang
    os: osx
    before_install:
      - brew update
    install:
      - brew install openssl
    script:
      - cd $TRAVIS_BUILD_DIR/seedminer
      - make
  - name: "bfCL - Ubuntu (gcc)"
    language: c
    compiler: gcc
    os: linux
    sudo: required
    env: SHARED=1 # To build mbedtls shared libs
    before_install:
      - sudo apt-get update
      - cd /home/travis/
      - git clone https://github.com/ARMmbed/mbedtls.git # Needed in order to compile bfCL
      - cd /home/travis/mbedtls/
      - git checkout $(git tag -l --sort -version:refname 'mbedtls-*' | head -n 1) # Checkout highest mbedtls tag version number
    install:
      - make lib
      - make check
      - sudo make install
      - sudo apt-get install -y ocl-icd-opencl-dev # OpenCL Headers & ICD Loader
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
  - name: "bfCL - macOS (clang)"
    language: c
    compiler: clang
    os: osx
    before_install:
      - brew update
    install:
      - brew install mbedtls
    script:
      - cd $TRAVIS_BUILD_DIR/bfCL
      - make
  - name: "Seedminer Launcher - Ubuntu" # We don't really need a macOS instance
    language: python
    python: 3.6
    os: linux
    sudo: false # Take advantage of a container-based environment
    cache: pip
    install:
      - pip install --upgrade pyflakes
    script:
      - cd $TRAVIS_BUILD_DIR/seedminer
      - pyflakes seedminer_launcher3.py
