language: generic
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
sudo: required
addons:
  apt:
    packages:
    - ocl-icd-opencl-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export SHARED=1; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd /home/travis/; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://tls.mbed.org/download/mbedtls-2.12.0-apache.tgz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xvf mbedtls-2.12.0-apache.tgz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd /home/travis/mbedtls-2.12.0/; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make check; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mbedtls; fi
script:
  - cd $TRAVIS_BUILD_DIR/bfCL
  - make
